# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Push Up Or Not?' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Push Up Or Not?
  pod 'GoogleMLKit/PoseDetection'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'SwiftSpinner'

  target 'Push Up Or Not?Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end
